// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/blog/blog.proto (package blog, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePostRequest, CreatePostResponse, GetPostsRequest, GetPostsResponse } from "./blog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service blog.BlogService
 */
export const BlogService = {
  typeName: "blog.BlogService",
  methods: {
    /**
     * @generated from rpc blog.BlogService.CreatePost
     */
    createPost: {
      name: "CreatePost",
      I: CreatePostRequest,
      O: CreatePostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.BlogService.GetPosts
     */
    getPosts: {
      name: "GetPosts",
      I: GetPostsRequest,
      O: GetPostsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

