// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file proto/dice/v1/dice.proto (package dice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum dice.v1.DieValue
 */
export enum DieValue {
  /**
   * @generated from enum value: DIE_VALUE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIE_VALUE_ONE = 1;
   */
  ONE = 1,

  /**
   * @generated from enum value: DIE_VALUE_TWO = 2;
   */
  TWO = 2,

  /**
   * @generated from enum value: DIE_VALUE_THREE = 3;
   */
  THREE = 3,

  /**
   * @generated from enum value: DIE_VALUE_FOUR = 4;
   */
  FOUR = 4,

  /**
   * @generated from enum value: DIE_VALUE_FIVE = 5;
   */
  FIVE = 5,

  /**
   * @generated from enum value: DIE_VALUE_SIX = 6;
   */
  SIX = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(DieValue)
proto3.util.setEnumType(DieValue, "dice.v1.DieValue", [
  { no: 0, name: "DIE_VALUE_UNSPECIFIED" },
  { no: 1, name: "DIE_VALUE_ONE" },
  { no: 2, name: "DIE_VALUE_TWO" },
  { no: 3, name: "DIE_VALUE_THREE" },
  { no: 4, name: "DIE_VALUE_FOUR" },
  { no: 5, name: "DIE_VALUE_FIVE" },
  { no: 6, name: "DIE_VALUE_SIX" },
]);

/**
 * @generated from message dice.v1.Vector3
 */
export class Vector3 extends Message<Vector3> {
  /**
   * @generated from field: float x = 1;
   */
  x = 0;

  /**
   * @generated from field: float y = 2;
   */
  y = 0;

  /**
   * @generated from field: float z = 3;
   */
  z = 0;

  constructor(data?: PartialMessage<Vector3>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.Vector3";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "x", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "y", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "z", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Vector3 {
    return new Vector3().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Vector3 {
    return new Vector3().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Vector3 {
    return new Vector3().fromJsonString(jsonString, options);
  }

  static equals(a: Vector3 | PlainMessage<Vector3> | undefined, b: Vector3 | PlainMessage<Vector3> | undefined): boolean {
    return proto3.util.equals(Vector3, a, b);
  }
}

/**
 * @generated from message dice.v1.Quaternion
 */
export class Quaternion extends Message<Quaternion> {
  /**
   * @generated from field: float x = 1;
   */
  x = 0;

  /**
   * @generated from field: float y = 2;
   */
  y = 0;

  /**
   * @generated from field: float z = 3;
   */
  z = 0;

  /**
   * @generated from field: float w = 4;
   */
  w = 0;

  constructor(data?: PartialMessage<Quaternion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.Quaternion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "x", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "y", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "z", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 4, name: "w", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Quaternion {
    return new Quaternion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Quaternion {
    return new Quaternion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Quaternion {
    return new Quaternion().fromJsonString(jsonString, options);
  }

  static equals(a: Quaternion | PlainMessage<Quaternion> | undefined, b: Quaternion | PlainMessage<Quaternion> | undefined): boolean {
    return proto3.util.equals(Quaternion, a, b);
  }
}

/**
 * @generated from message dice.v1.DieThrowSpec
 */
export class DieThrowSpec extends Message<DieThrowSpec> {
  /**
   * @generated from field: uint32 die_index = 1;
   */
  dieIndex = 0;

  /**
   * @generated from field: dice.v1.Vector3 position = 2;
   */
  position?: Vector3;

  /**
   * @generated from field: dice.v1.Quaternion rotation = 3;
   */
  rotation?: Quaternion;

  /**
   * @generated from field: dice.v1.Vector3 impulse = 4;
   */
  impulse?: Vector3;

  /**
   * @generated from field: dice.v1.Vector3 torque = 5;
   */
  torque?: Vector3;

  constructor(data?: PartialMessage<DieThrowSpec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DieThrowSpec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "position", kind: "message", T: Vector3 },
    { no: 3, name: "rotation", kind: "message", T: Quaternion },
    { no: 4, name: "impulse", kind: "message", T: Vector3 },
    { no: 5, name: "torque", kind: "message", T: Vector3 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DieThrowSpec {
    return new DieThrowSpec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DieThrowSpec {
    return new DieThrowSpec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DieThrowSpec {
    return new DieThrowSpec().fromJsonString(jsonString, options);
  }

  static equals(a: DieThrowSpec | PlainMessage<DieThrowSpec> | undefined, b: DieThrowSpec | PlainMessage<DieThrowSpec> | undefined): boolean {
    return proto3.util.equals(DieThrowSpec, a, b);
  }
}

/**
 * @generated from message dice.v1.RollSpec
 */
export class RollSpec extends Message<RollSpec> {
  /**
   * @generated from field: uint32 simulation_version = 1;
   */
  simulationVersion = 0;

  /**
   * @generated from field: uint32 roll_id = 2;
   */
  rollId = 0;

  /**
   * @generated from field: repeated dice.v1.DieThrowSpec dice = 3;
   */
  dice: DieThrowSpec[] = [];

  constructor(data?: PartialMessage<RollSpec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.RollSpec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "simulation_version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "roll_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "dice", kind: "message", T: DieThrowSpec, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollSpec {
    return new RollSpec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollSpec {
    return new RollSpec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollSpec {
    return new RollSpec().fromJsonString(jsonString, options);
  }

  static equals(a: RollSpec | PlainMessage<RollSpec> | undefined, b: RollSpec | PlainMessage<RollSpec> | undefined): boolean {
    return proto3.util.equals(RollSpec, a, b);
  }
}

/**
 * @generated from message dice.v1.DieResult
 */
export class DieResult extends Message<DieResult> {
  /**
   * @generated from field: uint32 die_index = 1;
   */
  dieIndex = 0;

  /**
   * @generated from field: dice.v1.DieValue value = 2;
   */
  value = DieValue.UNSPECIFIED;

  constructor(data?: PartialMessage<DieResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DieResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "value", kind: "enum", T: proto3.getEnumType(DieValue) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DieResult {
    return new DieResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DieResult {
    return new DieResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DieResult {
    return new DieResult().fromJsonString(jsonString, options);
  }

  static equals(a: DieResult | PlainMessage<DieResult> | undefined, b: DieResult | PlainMessage<DieResult> | undefined): boolean {
    return proto3.util.equals(DieResult, a, b);
  }
}

/**
 * @generated from message dice.v1.RollResult
 */
export class RollResult extends Message<RollResult> {
  /**
   * @generated from field: uint32 simulation_version = 1;
   */
  simulationVersion = 0;

  /**
   * @generated from field: uint32 roll_id = 2;
   */
  rollId = 0;

  /**
   * @generated from field: repeated dice.v1.DieResult dice = 3;
   */
  dice: DieResult[] = [];

  /**
   * @generated from field: uint32 total = 4;
   */
  total = 0;

  constructor(data?: PartialMessage<RollResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.RollResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "simulation_version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "roll_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "dice", kind: "message", T: DieResult, repeated: true },
    { no: 4, name: "total", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollResult {
    return new RollResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollResult {
    return new RollResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollResult {
    return new RollResult().fromJsonString(jsonString, options);
  }

  static equals(a: RollResult | PlainMessage<RollResult> | undefined, b: RollResult | PlainMessage<RollResult> | undefined): boolean {
    return proto3.util.equals(RollResult, a, b);
  }
}

