// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file proto/dice/v1/dice.proto (package dice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum dice.v1.RollMode
 */
export enum RollMode {
  /**
   * @generated from enum value: ROLL_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLL_MODE_ADD_NEW = 1;
   */
  ADD_NEW = 1,

  /**
   * @generated from enum value: ROLL_MODE_REROLL_EXISTING = 2;
   */
  REROLL_EXISTING = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(RollMode)
proto3.util.setEnumType(RollMode, "dice.v1.RollMode", [
  { no: 0, name: "ROLL_MODE_UNSPECIFIED" },
  { no: 1, name: "ROLL_MODE_ADD_NEW" },
  { no: 2, name: "ROLL_MODE_REROLL_EXISTING" },
]);

/**
 * @generated from enum dice.v1.DieFace
 */
export enum DieFace {
  /**
   * @generated from enum value: DIE_FACE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIE_FACE_ONE = 1;
   */
  ONE = 1,

  /**
   * @generated from enum value: DIE_FACE_TWO = 2;
   */
  TWO = 2,

  /**
   * @generated from enum value: DIE_FACE_THREE = 3;
   */
  THREE = 3,

  /**
   * @generated from enum value: DIE_FACE_FOUR = 4;
   */
  FOUR = 4,

  /**
   * @generated from enum value: DIE_FACE_FIVE = 5;
   */
  FIVE = 5,

  /**
   * @generated from enum value: DIE_FACE_SIX = 6;
   */
  SIX = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(DieFace)
proto3.util.setEnumType(DieFace, "dice.v1.DieFace", [
  { no: 0, name: "DIE_FACE_UNSPECIFIED" },
  { no: 1, name: "DIE_FACE_ONE" },
  { no: 2, name: "DIE_FACE_TWO" },
  { no: 3, name: "DIE_FACE_THREE" },
  { no: 4, name: "DIE_FACE_FOUR" },
  { no: 5, name: "DIE_FACE_FIVE" },
  { no: 6, name: "DIE_FACE_SIX" },
]);

/**
 * @generated from enum dice.v1.DieMotionState
 */
export enum DieMotionState {
  /**
   * @generated from enum value: DIE_MOTION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIE_MOTION_STATE_SETTLED = 1;
   */
  SETTLED = 1,

  /**
   * @generated from enum value: DIE_MOTION_STATE_ROLLING = 2;
   */
  ROLLING = 2,

  /**
   * @generated from enum value: DIE_MOTION_STATE_DRAGGED = 3;
   */
  DRAGGED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(DieMotionState)
proto3.util.setEnumType(DieMotionState, "dice.v1.DieMotionState", [
  { no: 0, name: "DIE_MOTION_STATE_UNSPECIFIED" },
  { no: 1, name: "DIE_MOTION_STATE_SETTLED" },
  { no: 2, name: "DIE_MOTION_STATE_ROLLING" },
  { no: 3, name: "DIE_MOTION_STATE_DRAGGED" },
]);

/**
 * @generated from enum dice.v1.CommandRejectionCode
 */
export enum CommandRejectionCode {
  /**
   * @generated from enum value: COMMAND_REJECTION_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COMMAND_REJECTION_CODE_INVALID_COMMAND = 1;
   */
  INVALID_COMMAND = 1,

  /**
   * @generated from enum value: COMMAND_REJECTION_CODE_NOT_OWNER = 2;
   */
  NOT_OWNER = 2,

  /**
   * @generated from enum value: COMMAND_REJECTION_CODE_CONFLICT = 3;
   */
  CONFLICT = 3,

  /**
   * @generated from enum value: COMMAND_REJECTION_CODE_STALE_STATE = 4;
   */
  STALE_STATE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(CommandRejectionCode)
proto3.util.setEnumType(CommandRejectionCode, "dice.v1.CommandRejectionCode", [
  { no: 0, name: "COMMAND_REJECTION_CODE_UNSPECIFIED" },
  { no: 1, name: "COMMAND_REJECTION_CODE_INVALID_COMMAND" },
  { no: 2, name: "COMMAND_REJECTION_CODE_NOT_OWNER" },
  { no: 3, name: "COMMAND_REJECTION_CODE_CONFLICT" },
  { no: 4, name: "COMMAND_REJECTION_CODE_STALE_STATE" },
]);

/**
 * All table coordinates are server-owned, double-precision world units.
 *
 * @generated from message dice.v1.WorldVector3
 */
export class WorldVector3 extends Message<WorldVector3> {
  /**
   * @generated from field: double x = 1;
   */
  x = 0;

  /**
   * @generated from field: double y = 2;
   */
  y = 0;

  /**
   * @generated from field: double z = 3;
   */
  z = 0;

  constructor(data?: PartialMessage<WorldVector3>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.WorldVector3";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldVector3 {
    return new WorldVector3().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldVector3 {
    return new WorldVector3().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldVector3 {
    return new WorldVector3().fromJsonString(jsonString, options);
  }

  static equals(a: WorldVector3 | PlainMessage<WorldVector3> | undefined, b: WorldVector3 | PlainMessage<WorldVector3> | undefined): boolean {
    return proto3.util.equals(WorldVector3, a, b);
  }
}

/**
 * @generated from message dice.v1.WorldQuaternion
 */
export class WorldQuaternion extends Message<WorldQuaternion> {
  /**
   * @generated from field: double x = 1;
   */
  x = 0;

  /**
   * @generated from field: double y = 2;
   */
  y = 0;

  /**
   * @generated from field: double z = 3;
   */
  z = 0;

  /**
   * @generated from field: double w = 4;
   */
  w = 0;

  constructor(data?: PartialMessage<WorldQuaternion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.WorldQuaternion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "w", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldQuaternion {
    return new WorldQuaternion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldQuaternion {
    return new WorldQuaternion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldQuaternion {
    return new WorldQuaternion().fromJsonString(jsonString, options);
  }

  static equals(a: WorldQuaternion | PlainMessage<WorldQuaternion> | undefined, b: WorldQuaternion | PlainMessage<WorldQuaternion> | undefined): boolean {
    return proto3.util.equals(WorldQuaternion, a, b);
  }
}

/**
 * @generated from message dice.v1.WorldTransform
 */
export class WorldTransform extends Message<WorldTransform> {
  /**
   * @generated from field: dice.v1.WorldVector3 position = 1;
   */
  position?: WorldVector3;

  /**
   * @generated from field: dice.v1.WorldQuaternion rotation = 2;
   */
  rotation?: WorldQuaternion;

  constructor(data?: PartialMessage<WorldTransform>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.WorldTransform";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "position", kind: "message", T: WorldVector3 },
    { no: 2, name: "rotation", kind: "message", T: WorldQuaternion },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldTransform {
    return new WorldTransform().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldTransform {
    return new WorldTransform().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldTransform {
    return new WorldTransform().fromJsonString(jsonString, options);
  }

  static equals(a: WorldTransform | PlainMessage<WorldTransform> | undefined, b: WorldTransform | PlainMessage<WorldTransform> | undefined): boolean {
    return proto3.util.equals(WorldTransform, a, b);
  }
}

/**
 * @generated from message dice.v1.TablePoint
 */
export class TablePoint extends Message<TablePoint> {
  /**
   * @generated from field: double x = 1;
   */
  x = 0;

  /**
   * @generated from field: double z = 2;
   */
  z = 0;

  constructor(data?: PartialMessage<TablePoint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.TablePoint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TablePoint {
    return new TablePoint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TablePoint {
    return new TablePoint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TablePoint {
    return new TablePoint().fromJsonString(jsonString, options);
  }

  static equals(a: TablePoint | PlainMessage<TablePoint> | undefined, b: TablePoint | PlainMessage<TablePoint> | undefined): boolean {
    return proto3.util.equals(TablePoint, a, b);
  }
}

/**
 * @generated from message dice.v1.TableBounds
 */
export class TableBounds extends Message<TableBounds> {
  /**
   * @generated from field: double min_x = 1;
   */
  minX = 0;

  /**
   * @generated from field: double max_x = 2;
   */
  maxX = 0;

  /**
   * @generated from field: double min_z = 3;
   */
  minZ = 0;

  /**
   * @generated from field: double max_z = 4;
   */
  maxZ = 0;

  constructor(data?: PartialMessage<TableBounds>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.TableBounds";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "min_x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "max_x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "min_z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "max_z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableBounds {
    return new TableBounds().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableBounds {
    return new TableBounds().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableBounds {
    return new TableBounds().fromJsonString(jsonString, options);
  }

  static equals(a: TableBounds | PlainMessage<TableBounds> | undefined, b: TableBounds | PlainMessage<TableBounds> | undefined): boolean {
    return proto3.util.equals(TableBounds, a, b);
  }
}

/**
 * @generated from message dice.v1.DieResult
 */
export class DieResult extends Message<DieResult> {
  /**
   * @generated from field: uint32 die_index = 1;
   */
  dieIndex = 0;

  /**
   * @generated from field: dice.v1.DieFace face = 2;
   */
  face = DieFace.UNSPECIFIED;

  /**
   * @generated from field: string die_id = 3;
   */
  dieId = "";

  /**
   * @generated from field: string die_definition_id = 4;
   */
  dieDefinitionId = "";

  constructor(data?: PartialMessage<DieResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DieResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "face", kind: "enum", T: proto3.getEnumType(DieFace) },
    { no: 3, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "die_definition_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DieResult {
    return new DieResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DieResult {
    return new DieResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DieResult {
    return new DieResult().fromJsonString(jsonString, options);
  }

  static equals(a: DieResult | PlainMessage<DieResult> | undefined, b: DieResult | PlainMessage<DieResult> | undefined): boolean {
    return proto3.util.equals(DieResult, a, b);
  }
}

/**
 * @generated from message dice.v1.RollResult
 */
export class RollResult extends Message<RollResult> {
  /**
   * @generated from field: uint32 simulation_version = 1;
   */
  simulationVersion = 0;

  /**
   * @generated from field: string roll_id = 2;
   */
  rollId = "";

  /**
   * @generated from field: repeated dice.v1.DieResult dice = 3;
   */
  dice: DieResult[] = [];

  constructor(data?: PartialMessage<RollResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.RollResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "simulation_version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "roll_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "dice", kind: "message", T: DieResult, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollResult {
    return new RollResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollResult {
    return new RollResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollResult {
    return new RollResult().fromJsonString(jsonString, options);
  }

  static equals(a: RollResult | PlainMessage<RollResult> | undefined, b: RollResult | PlainMessage<RollResult> | undefined): boolean {
    return proto3.util.equals(RollResult, a, b);
  }
}

/**
 * @generated from message dice.v1.TableDieState
 */
export class TableDieState extends Message<TableDieState> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: dice.v1.DieFace face = 2;
   */
  face = DieFace.UNSPECIFIED;

  /**
   * @generated from field: dice.v1.WorldTransform transform = 3;
   */
  transform?: WorldTransform;

  /**
   * @generated from field: string owner_player_id = 4;
   */
  ownerPlayerId = "";

  /**
   * @generated from field: uint64 revision = 5;
   */
  revision = protoInt64.zero;

  /**
   * @generated from field: string die_definition_id = 6;
   */
  dieDefinitionId = "";

  /**
   * @generated from field: dice.v1.DieMotionState motion = 7;
   */
  motion = DieMotionState.UNSPECIFIED;

  /**
   * @generated from field: string active_roll_id = 8;
   */
  activeRollId = "";

  constructor(data?: PartialMessage<TableDieState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.TableDieState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "face", kind: "enum", T: proto3.getEnumType(DieFace) },
    { no: 3, name: "transform", kind: "message", T: WorldTransform },
    { no: 4, name: "owner_player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "revision", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "die_definition_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "motion", kind: "enum", T: proto3.getEnumType(DieMotionState) },
    { no: 8, name: "active_roll_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableDieState {
    return new TableDieState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableDieState {
    return new TableDieState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableDieState {
    return new TableDieState().fromJsonString(jsonString, options);
  }

  static equals(a: TableDieState | PlainMessage<TableDieState> | undefined, b: TableDieState | PlainMessage<TableDieState> | undefined): boolean {
    return proto3.util.equals(TableDieState, a, b);
  }
}

/**
 * @generated from message dice.v1.ActiveRoll
 */
export class ActiveRoll extends Message<ActiveRoll> {
  /**
   * @generated from field: string roll_id = 1;
   */
  rollId = "";

  /**
   * @generated from field: string roller_id = 2;
   */
  rollerId = "";

  /**
   * @generated from field: dice.v1.RollMode mode = 3;
   */
  mode = RollMode.UNSPECIFIED;

  /**
   * @generated from field: repeated string target_die_ids = 4;
   */
  targetDieIds: string[] = [];

  /**
   * @generated from field: uint64 start_tick = 5;
   */
  startTick = protoInt64.zero;

  constructor(data?: PartialMessage<ActiveRoll>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.ActiveRoll";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "roll_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "roller_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "mode", kind: "enum", T: proto3.getEnumType(RollMode) },
    { no: 4, name: "target_die_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "start_tick", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActiveRoll {
    return new ActiveRoll().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActiveRoll {
    return new ActiveRoll().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActiveRoll {
    return new ActiveRoll().fromJsonString(jsonString, options);
  }

  static equals(a: ActiveRoll | PlainMessage<ActiveRoll> | undefined, b: ActiveRoll | PlainMessage<ActiveRoll> | undefined): boolean {
    return proto3.util.equals(ActiveRoll, a, b);
  }
}

/**
 * @generated from message dice.v1.ActiveDrag
 */
export class ActiveDrag extends Message<ActiveDrag> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string player_id = 2;
   */
  playerId = "";

  /**
   * @generated from field: string interaction_id = 3;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 4;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 5;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<ActiveDrag>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.ActiveDrag";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActiveDrag {
    return new ActiveDrag().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActiveDrag {
    return new ActiveDrag().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActiveDrag {
    return new ActiveDrag().fromJsonString(jsonString, options);
  }

  static equals(a: ActiveDrag | PlainMessage<ActiveDrag> | undefined, b: ActiveDrag | PlainMessage<ActiveDrag> | undefined): boolean {
    return proto3.util.equals(ActiveDrag, a, b);
  }
}

/**
 * @generated from message dice.v1.TableSnapshot
 */
export class TableSnapshot extends Message<TableSnapshot> {
  /**
   * @generated from field: string table_id = 1;
   */
  tableId = "";

  /**
   * @generated from field: uint64 revision = 2;
   */
  revision = protoInt64.zero;

  /**
   * @generated from field: repeated dice.v1.TableDieState dice = 3;
   */
  dice: TableDieState[] = [];

  /**
   * @generated from field: repeated dice.v1.ActiveRoll active_rolls = 4;
   */
  activeRolls: ActiveRoll[] = [];

  /**
   * @generated from field: repeated dice.v1.ActiveDrag active_drags = 5;
   */
  activeDrags: ActiveDrag[] = [];

  /**
   * @generated from field: uint64 physics_tick = 6;
   */
  physicsTick = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TableBounds bounds = 7;
   */
  bounds?: TableBounds;

  constructor(data?: PartialMessage<TableSnapshot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.TableSnapshot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "table_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "revision", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "dice", kind: "message", T: TableDieState, repeated: true },
    { no: 4, name: "active_rolls", kind: "message", T: ActiveRoll, repeated: true },
    { no: 5, name: "active_drags", kind: "message", T: ActiveDrag, repeated: true },
    { no: 6, name: "physics_tick", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "bounds", kind: "message", T: TableBounds },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableSnapshot {
    return new TableSnapshot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableSnapshot {
    return new TableSnapshot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableSnapshot {
    return new TableSnapshot().fromJsonString(jsonString, options);
  }

  static equals(a: TableSnapshot | PlainMessage<TableSnapshot> | undefined, b: TableSnapshot | PlainMessage<TableSnapshot> | undefined): boolean {
    return proto3.util.equals(TableSnapshot, a, b);
  }
}

/**
 * @generated from message dice.v1.RollStarted
 */
export class RollStarted extends Message<RollStarted> {
  /**
   * @generated from field: string roll_id = 1;
   */
  rollId = "";

  /**
   * @generated from field: string roller_id = 2;
   */
  rollerId = "";

  /**
   * @generated from field: dice.v1.RollMode mode = 3;
   */
  mode = RollMode.UNSPECIFIED;

  /**
   * @generated from field: repeated dice.v1.TableDieState dice = 4;
   */
  dice: TableDieState[] = [];

  /**
   * @generated from field: uint64 start_tick = 5;
   */
  startTick = protoInt64.zero;

  constructor(data?: PartialMessage<RollStarted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.RollStarted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "roll_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "roller_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "mode", kind: "enum", T: proto3.getEnumType(RollMode) },
    { no: 4, name: "dice", kind: "message", T: TableDieState, repeated: true },
    { no: 5, name: "start_tick", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollStarted {
    return new RollStarted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollStarted {
    return new RollStarted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollStarted {
    return new RollStarted().fromJsonString(jsonString, options);
  }

  static equals(a: RollStarted | PlainMessage<RollStarted> | undefined, b: RollStarted | PlainMessage<RollStarted> | undefined): boolean {
    return proto3.util.equals(RollStarted, a, b);
  }
}

/**
 * @generated from message dice.v1.RollCompleted
 */
export class RollCompleted extends Message<RollCompleted> {
  /**
   * @generated from field: string roll_id = 1;
   */
  rollId = "";

  /**
   * @generated from field: string roller_id = 2;
   */
  rollerId = "";

  /**
   * @generated from field: dice.v1.RollResult result = 3;
   */
  result?: RollResult;

  /**
   * Includes every die whose transform or face changed during the shared
   * simulation, including settled dice displaced by another player's roll.
   *
   * @generated from field: repeated dice.v1.TableDieState changed_dice = 4;
   */
  changedDice: TableDieState[] = [];

  /**
   * @generated from field: uint64 completed_tick = 5;
   */
  completedTick = protoInt64.zero;

  constructor(data?: PartialMessage<RollCompleted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.RollCompleted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "roll_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "roller_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "result", kind: "message", T: RollResult },
    { no: 4, name: "changed_dice", kind: "message", T: TableDieState, repeated: true },
    { no: 5, name: "completed_tick", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollCompleted {
    return new RollCompleted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollCompleted {
    return new RollCompleted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollCompleted {
    return new RollCompleted().fromJsonString(jsonString, options);
  }

  static equals(a: RollCompleted | PlainMessage<RollCompleted> | undefined, b: RollCompleted | PlainMessage<RollCompleted> | undefined): boolean {
    return proto3.util.equals(RollCompleted, a, b);
  }
}

/**
 * @generated from message dice.v1.DragStarted
 */
export class DragStarted extends Message<DragStarted> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string player_id = 2;
   */
  playerId = "";

  /**
   * @generated from field: string interaction_id = 3;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 4;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 5;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<DragStarted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DragStarted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DragStarted {
    return new DragStarted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DragStarted {
    return new DragStarted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DragStarted {
    return new DragStarted().fromJsonString(jsonString, options);
  }

  static equals(a: DragStarted | PlainMessage<DragStarted> | undefined, b: DragStarted | PlainMessage<DragStarted> | undefined): boolean {
    return proto3.util.equals(DragStarted, a, b);
  }
}

/**
 * @generated from message dice.v1.DragUpdated
 */
export class DragUpdated extends Message<DragUpdated> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string player_id = 2;
   */
  playerId = "";

  /**
   * @generated from field: string interaction_id = 3;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 4;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 5;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<DragUpdated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DragUpdated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DragUpdated {
    return new DragUpdated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DragUpdated {
    return new DragUpdated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DragUpdated {
    return new DragUpdated().fromJsonString(jsonString, options);
  }

  static equals(a: DragUpdated | PlainMessage<DragUpdated> | undefined, b: DragUpdated | PlainMessage<DragUpdated> | undefined): boolean {
    return proto3.util.equals(DragUpdated, a, b);
  }
}

/**
 * @generated from message dice.v1.DragEnded
 */
export class DragEnded extends Message<DragEnded> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string player_id = 2;
   */
  playerId = "";

  /**
   * @generated from field: string interaction_id = 3;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 4;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 5;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<DragEnded>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DragEnded";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DragEnded {
    return new DragEnded().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DragEnded {
    return new DragEnded().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DragEnded {
    return new DragEnded().fromJsonString(jsonString, options);
  }

  static equals(a: DragEnded | PlainMessage<DragEnded> | undefined, b: DragEnded | PlainMessage<DragEnded> | undefined): boolean {
    return proto3.util.equals(DragEnded, a, b);
  }
}

/**
 * @generated from message dice.v1.TableEvent
 */
export class TableEvent extends Message<TableEvent> {
  /**
   * @generated from field: string table_id = 1;
   */
  tableId = "";

  /**
   * @generated from field: uint64 revision = 2;
   */
  revision = protoInt64.zero;

  /**
   * @generated from oneof dice.v1.TableEvent.payload
   */
  payload: {
    /**
     * @generated from field: dice.v1.RollStarted roll_started = 3;
     */
    value: RollStarted;
    case: "rollStarted";
  } | {
    /**
     * @generated from field: dice.v1.RollCompleted roll_completed = 4;
     */
    value: RollCompleted;
    case: "rollCompleted";
  } | {
    /**
     * @generated from field: dice.v1.DragStarted drag_started = 5;
     */
    value: DragStarted;
    case: "dragStarted";
  } | {
    /**
     * @generated from field: dice.v1.DragUpdated drag_updated = 6;
     */
    value: DragUpdated;
    case: "dragUpdated";
  } | {
    /**
     * @generated from field: dice.v1.DragEnded drag_ended = 7;
     */
    value: DragEnded;
    case: "dragEnded";
  } | {
    /**
     * @generated from field: dice.v1.TableSnapshot snapshot = 8;
     */
    value: TableSnapshot;
    case: "snapshot";
  } | { case: undefined; value?: undefined } = { case: undefined };

  /**
   * @generated from field: string source_request_id = 9;
   */
  sourceRequestId = "";

  /**
   * @generated from field: dice.v1.TableBounds bounds = 10;
   */
  bounds?: TableBounds;

  constructor(data?: PartialMessage<TableEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.TableEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "table_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "revision", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "roll_started", kind: "message", T: RollStarted, oneof: "payload" },
    { no: 4, name: "roll_completed", kind: "message", T: RollCompleted, oneof: "payload" },
    { no: 5, name: "drag_started", kind: "message", T: DragStarted, oneof: "payload" },
    { no: 6, name: "drag_updated", kind: "message", T: DragUpdated, oneof: "payload" },
    { no: 7, name: "drag_ended", kind: "message", T: DragEnded, oneof: "payload" },
    { no: 8, name: "snapshot", kind: "message", T: TableSnapshot, oneof: "payload" },
    { no: 9, name: "source_request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "bounds", kind: "message", T: TableBounds },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableEvent {
    return new TableEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableEvent {
    return new TableEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableEvent {
    return new TableEvent().fromJsonString(jsonString, options);
  }

  static equals(a: TableEvent | PlainMessage<TableEvent> | undefined, b: TableEvent | PlainMessage<TableEvent> | undefined): boolean {
    return proto3.util.equals(TableEvent, a, b);
  }
}

/**
 * @generated from message dice.v1.JoinRoom
 */
export class JoinRoom extends Message<JoinRoom> {
  /**
   * @generated from field: string resume_token = 1;
   */
  resumeToken = "";

  constructor(data?: PartialMessage<JoinRoom>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.JoinRoom";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resume_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JoinRoom {
    return new JoinRoom().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JoinRoom {
    return new JoinRoom().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JoinRoom {
    return new JoinRoom().fromJsonString(jsonString, options);
  }

  static equals(a: JoinRoom | PlainMessage<JoinRoom> | undefined, b: JoinRoom | PlainMessage<JoinRoom> | undefined): boolean {
    return proto3.util.equals(JoinRoom, a, b);
  }
}

/**
 * @generated from message dice.v1.StartRollCommand
 */
export class StartRollCommand extends Message<StartRollCommand> {
  /**
   * @generated from field: dice.v1.RollMode mode = 1;
   */
  mode = RollMode.UNSPECIFIED;

  /**
   * Empty for the first ADD_NEW roll. The server creates the standard twelve.
   *
   * @generated from field: repeated string target_die_ids = 2;
   */
  targetDieIds: string[] = [];

  constructor(data?: PartialMessage<StartRollCommand>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.StartRollCommand";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mode", kind: "enum", T: proto3.getEnumType(RollMode) },
    { no: 2, name: "target_die_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartRollCommand {
    return new StartRollCommand().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartRollCommand {
    return new StartRollCommand().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartRollCommand {
    return new StartRollCommand().fromJsonString(jsonString, options);
  }

  static equals(a: StartRollCommand | PlainMessage<StartRollCommand> | undefined, b: StartRollCommand | PlainMessage<StartRollCommand> | undefined): boolean {
    return proto3.util.equals(StartRollCommand, a, b);
  }
}

/**
 * @generated from message dice.v1.StartDragCommand
 */
export class StartDragCommand extends Message<StartDragCommand> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string interaction_id = 2;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 3;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 4;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<StartDragCommand>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.StartDragCommand";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartDragCommand {
    return new StartDragCommand().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartDragCommand {
    return new StartDragCommand().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartDragCommand {
    return new StartDragCommand().fromJsonString(jsonString, options);
  }

  static equals(a: StartDragCommand | PlainMessage<StartDragCommand> | undefined, b: StartDragCommand | PlainMessage<StartDragCommand> | undefined): boolean {
    return proto3.util.equals(StartDragCommand, a, b);
  }
}

/**
 * @generated from message dice.v1.UpdateDragCommand
 */
export class UpdateDragCommand extends Message<UpdateDragCommand> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string interaction_id = 2;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 3;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 4;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<UpdateDragCommand>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.UpdateDragCommand";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateDragCommand {
    return new UpdateDragCommand().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateDragCommand {
    return new UpdateDragCommand().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateDragCommand {
    return new UpdateDragCommand().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateDragCommand | PlainMessage<UpdateDragCommand> | undefined, b: UpdateDragCommand | PlainMessage<UpdateDragCommand> | undefined): boolean {
    return proto3.util.equals(UpdateDragCommand, a, b);
  }
}

/**
 * @generated from message dice.v1.EndDragCommand
 */
export class EndDragCommand extends Message<EndDragCommand> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: string interaction_id = 2;
   */
  interactionId = "";

  /**
   * @generated from field: uint64 sequence = 3;
   */
  sequence = protoInt64.zero;

  /**
   * @generated from field: dice.v1.TablePoint target = 4;
   */
  target?: TablePoint;

  constructor(data?: PartialMessage<EndDragCommand>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.EndDragCommand";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "target", kind: "message", T: TablePoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EndDragCommand {
    return new EndDragCommand().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EndDragCommand {
    return new EndDragCommand().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EndDragCommand {
    return new EndDragCommand().fromJsonString(jsonString, options);
  }

  static equals(a: EndDragCommand | PlainMessage<EndDragCommand> | undefined, b: EndDragCommand | PlainMessage<EndDragCommand> | undefined): boolean {
    return proto3.util.equals(EndDragCommand, a, b);
  }
}

/**
 * @generated from message dice.v1.ClientMessage
 */
export class ClientMessage extends Message<ClientMessage> {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId = "";

  /**
   * @generated from oneof dice.v1.ClientMessage.payload
   */
  payload: {
    /**
     * @generated from field: dice.v1.JoinRoom join = 2;
     */
    value: JoinRoom;
    case: "join";
  } | {
    /**
     * @generated from field: dice.v1.StartRollCommand start_roll = 3;
     */
    value: StartRollCommand;
    case: "startRoll";
  } | {
    /**
     * @generated from field: dice.v1.StartDragCommand start_drag = 4;
     */
    value: StartDragCommand;
    case: "startDrag";
  } | {
    /**
     * @generated from field: dice.v1.UpdateDragCommand update_drag = 5;
     */
    value: UpdateDragCommand;
    case: "updateDrag";
  } | {
    /**
     * @generated from field: dice.v1.EndDragCommand end_drag = 6;
     */
    value: EndDragCommand;
    case: "endDrag";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ClientMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.ClientMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "join", kind: "message", T: JoinRoom, oneof: "payload" },
    { no: 3, name: "start_roll", kind: "message", T: StartRollCommand, oneof: "payload" },
    { no: 4, name: "start_drag", kind: "message", T: StartDragCommand, oneof: "payload" },
    { no: 5, name: "update_drag", kind: "message", T: UpdateDragCommand, oneof: "payload" },
    { no: 6, name: "end_drag", kind: "message", T: EndDragCommand, oneof: "payload" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientMessage {
    return new ClientMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientMessage {
    return new ClientMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientMessage {
    return new ClientMessage().fromJsonString(jsonString, options);
  }

  static equals(a: ClientMessage | PlainMessage<ClientMessage> | undefined, b: ClientMessage | PlainMessage<ClientMessage> | undefined): boolean {
    return proto3.util.equals(ClientMessage, a, b);
  }
}

/**
 * @generated from message dice.v1.Welcome
 */
export class Welcome extends Message<Welcome> {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId = "";

  /**
   * @generated from field: string resume_token = 2;
   */
  resumeToken = "";

  /**
   * @generated from field: dice.v1.TableSnapshot snapshot = 3;
   */
  snapshot?: TableSnapshot;

  constructor(data?: PartialMessage<Welcome>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.Welcome";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "resume_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "snapshot", kind: "message", T: TableSnapshot },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Welcome {
    return new Welcome().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Welcome {
    return new Welcome().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Welcome {
    return new Welcome().fromJsonString(jsonString, options);
  }

  static equals(a: Welcome | PlainMessage<Welcome> | undefined, b: Welcome | PlainMessage<Welcome> | undefined): boolean {
    return proto3.util.equals(Welcome, a, b);
  }
}

/**
 * @generated from message dice.v1.CommandRejected
 */
export class CommandRejected extends Message<CommandRejected> {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId = "";

  /**
   * @generated from field: dice.v1.CommandRejectionCode code = 2;
   */
  code = CommandRejectionCode.UNSPECIFIED;

  /**
   * @generated from field: string message = 3;
   */
  message = "";

  constructor(data?: PartialMessage<CommandRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.CommandRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "enum", T: proto3.getEnumType(CommandRejectionCode) },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommandRejected {
    return new CommandRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommandRejected {
    return new CommandRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommandRejected {
    return new CommandRejected().fromJsonString(jsonString, options);
  }

  static equals(a: CommandRejected | PlainMessage<CommandRejected> | undefined, b: CommandRejected | PlainMessage<CommandRejected> | undefined): boolean {
    return proto3.util.equals(CommandRejected, a, b);
  }
}

/**
 * @generated from message dice.v1.DieTransform
 */
export class DieTransform extends Message<DieTransform> {
  /**
   * @generated from field: string die_id = 1;
   */
  dieId = "";

  /**
   * @generated from field: dice.v1.WorldTransform transform = 2;
   */
  transform?: WorldTransform;

  /**
   * @generated from field: dice.v1.DieMotionState motion = 3;
   */
  motion = DieMotionState.UNSPECIFIED;

  /**
   * @generated from field: uint64 revision = 4;
   */
  revision = protoInt64.zero;

  constructor(data?: PartialMessage<DieTransform>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.DieTransform";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "die_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "transform", kind: "message", T: WorldTransform },
    { no: 3, name: "motion", kind: "enum", T: proto3.getEnumType(DieMotionState) },
    { no: 4, name: "revision", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DieTransform {
    return new DieTransform().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DieTransform {
    return new DieTransform().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DieTransform {
    return new DieTransform().fromJsonString(jsonString, options);
  }

  static equals(a: DieTransform | PlainMessage<DieTransform> | undefined, b: DieTransform | PlainMessage<DieTransform> | undefined): boolean {
    return proto3.util.equals(DieTransform, a, b);
  }
}

/**
 * @generated from message dice.v1.PhysicsFrame
 */
export class PhysicsFrame extends Message<PhysicsFrame> {
  /**
   * @generated from field: uint64 tick = 1;
   */
  tick = protoInt64.zero;

  /**
   * @generated from field: repeated dice.v1.DieTransform dice = 2;
   */
  dice: DieTransform[] = [];

  /**
   * @generated from field: dice.v1.TableBounds bounds = 3;
   */
  bounds?: TableBounds;

  constructor(data?: PartialMessage<PhysicsFrame>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.PhysicsFrame";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tick", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "dice", kind: "message", T: DieTransform, repeated: true },
    { no: 3, name: "bounds", kind: "message", T: TableBounds },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PhysicsFrame {
    return new PhysicsFrame().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PhysicsFrame {
    return new PhysicsFrame().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PhysicsFrame {
    return new PhysicsFrame().fromJsonString(jsonString, options);
  }

  static equals(a: PhysicsFrame | PlainMessage<PhysicsFrame> | undefined, b: PhysicsFrame | PlainMessage<PhysicsFrame> | undefined): boolean {
    return proto3.util.equals(PhysicsFrame, a, b);
  }
}

/**
 * @generated from message dice.v1.ServerMessage
 */
export class ServerMessage extends Message<ServerMessage> {
  /**
   * @generated from oneof dice.v1.ServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: dice.v1.Welcome welcome = 1;
     */
    value: Welcome;
    case: "welcome";
  } | {
    /**
     * @generated from field: dice.v1.TableEvent event = 2;
     */
    value: TableEvent;
    case: "event";
  } | {
    /**
     * @generated from field: dice.v1.CommandRejected rejected = 3;
     */
    value: CommandRejected;
    case: "rejected";
  } | {
    /**
     * @generated from field: dice.v1.PhysicsFrame physics_frame = 4;
     */
    value: PhysicsFrame;
    case: "physicsFrame";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ServerMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dice.v1.ServerMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "welcome", kind: "message", T: Welcome, oneof: "payload" },
    { no: 2, name: "event", kind: "message", T: TableEvent, oneof: "payload" },
    { no: 3, name: "rejected", kind: "message", T: CommandRejected, oneof: "payload" },
    { no: 4, name: "physics_frame", kind: "message", T: PhysicsFrame, oneof: "payload" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerMessage {
    return new ServerMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerMessage {
    return new ServerMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerMessage {
    return new ServerMessage().fromJsonString(jsonString, options);
  }

  static equals(a: ServerMessage | PlainMessage<ServerMessage> | undefined, b: ServerMessage | PlainMessage<ServerMessage> | undefined): boolean {
    return proto3.util.equals(ServerMessage, a, b);
  }
}

