# Generated by Django 3.1 on 2020-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20200817_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player1',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.TextField(default='0'),
        ),
    ]
