# Generated by Django 3.1 on 2020-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_room_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='player',
            name='in_room',
        ),
        migrations.AddField(
            model_name='player',
            name='needs_match',
            field=models.BooleanField(default=True),
        ),
    ]
