# Generated by Django 3.1 on 2020-08-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_auto_20200819_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
