# Generated by Django 3.1 on 2020-08-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_auto_20200819_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opponent',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='lobby.player'),
            preserve_default=False,
        ),
    ]
