# Generated by Django 3.1 on 2020-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_player_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opponent',
            field=models.IntegerField(),
        ),
    ]
