# Generated by Django 3.1 on 2020-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField(default='')),
                ('command', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.IntegerField(default=0)),
                ('player2', models.IntegerField(default=0)),
                ('whos_turn', models.IntegerField(default=0)),
                ('player1Cards', models.JSONField(default=dict)),
                ('player2Cards', models.JSONField(default=dict)),
            ],
        ),
    ]
