# Generated by Django 3.1 on 2020-08-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1Cards',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2Cards',
            field=models.JSONField(default=str),
        ),
    ]
