# Generated by Django 3.1 on 2020-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
