// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/card/card.proto (package card, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateCardRequest, CreateCardResponse, CreateCardTemplateRequest, CreateCardTemplateResponse, DeleteCardRequest, DeleteCardResponse, GenerateCardsRequest, GenerateCardsResponse, GetCardsRequest, GetCardsResponse, NewCardRequest, NewCardResponse } from "./card_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service card.CardService
 */
export const CardService = {
  typeName: "card.CardService",
  methods: {
    /**
     * @generated from rpc card.CardService.GetCards
     */
    getCards: {
      name: "GetCards",
      I: GetCardsRequest,
      O: GetCardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc card.CardService.NewCard
     */
    newCard: {
      name: "NewCard",
      I: NewCardRequest,
      O: NewCardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc card.CardService.DeleteCard
     */
    deleteCard: {
      name: "DeleteCard",
      I: DeleteCardRequest,
      O: DeleteCardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc card.CardService.GenerateCards
     */
    generateCards: {
      name: "GenerateCards",
      I: GenerateCardsRequest,
      O: GenerateCardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc card.CardService.CreateCardTemplate
     */
    createCardTemplate: {
      name: "CreateCardTemplate",
      I: CreateCardTemplateRequest,
      O: CreateCardTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc card.CardService.CreateCard
     */
    createCard: {
      name: "CreateCard",
      I: CreateCardRequest,
      O: CreateCardResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

