// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/card/deck.proto (package card, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service card.DeckService
 */
export const DeckService = {
  typeName: "card.DeckService",
  methods: {
  }
} as const;

